language: ruby
rvm: 2.5
cache: bundler
before_install:
    - gem update --system
    - gem install bundler
script:
    - bundler exec jekyll build
    - bundler exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: _site
  target_branch: gh-pages
